import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          
          {children}
        </ClerkProvider>

        <Toaster toastOptions={{duration: 1500}}/>

      </body>
    </html>
  );
}
